### ISSUE TITLE
Could there be a requirements.txt?

### ISSUE THREAD

**Issue by sck** [cgreer/alpha-zero-boosted#1]
`pip3 freeze > requirements.txt`

Would make running the code in one's own python environment a lot easier!

**Comment by pfbrousseau** [comment]
I've added a requirements file. Note that it's much cleaner than the freeze you'll get, but these should be everything you need to run a base example.
If you face any problems installing, please comment here!

Make sure you install `libomp` If you get ```python3.7/site-packages/treelite_runtime/lib/libtreelite_runtime.dylib
  Reason: image not found```

**Comment by sck** [comment]
Thank you!

I can now run both:

`python3.7 play.py connect_four gbdt-1 human-1 5.0`

and

`python3.7 train_bot.py connect_four gbdt 10`

in a newly setup python environment, after running `sudo pip3.7 install -r requirements.txt`

**Comment by cgreer** [comment]
Awesome! I didn't originally intend to share this so soon, so there will likely be issues/ugliness/etc. But if you're feeling brave I'm happy to answer questions and fix things when they come up until the code is more shareable/stable.
